[tox]
minversion = 4.0.0

[testenv]
description = run the tests with pytest
package = wheel
wheel_build_env = .pkg
deps =
    pytest>=6
commands =
    pytest {tty:--color=yes} {posargs} tests/unit

[testenv:integration]
commands =
    pytest {tty:--color=yes} {posargs} tests/integration

passenv = FABRIC_*

[testenv:benchmarks]
commands =
    pytest {tty:--color=yes} {posargs} tests/benchmarks

[testenv:docs]
# An environment for generanting docs.
deps =
     sphinx
     sphinx-autodoc-typehints
     furo

commands =
    sphinx-build -W -b html {toxinidir}/docs/source/ {toxinidir}/docs/build/html

[testenv:lint]
# An environment for linting code.
deps =
    ruff>=0.4

skip_install = True

commands =
    ruff check fabrictestbed_extensions tests
    ruff format --check fabrictestbed_extensions tests

[testenv:format]
# An environment for formatting code.
deps =
    ruff>=0.4

skip_install = True

commands =
    ruff check --fix fabrictestbed_extensions tests
    ruff format fabrictestbed_extensions tests
