# Run some code checks with GitHub Actions.

name: Code checks

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:

  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: 'pip'  # cache pip dependencies

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install black isort flake8

      - name: Run "black --check"
        run: |
          python -m black --check .

      - name: Run "isort --check"
        run: |
          python -m isort --check --profile black .

      # TODO: flake8 depends on the version of Python, so in order to
      # surface potential problems when running with different Python
      # versions, we will need to run flake8 with each of them, not
      # just the one Python version used in this workflow.
      - name: Run flake8
        run: |
          python -m flake8
